zkcrypto eip-4844 partial implementation (#168)
* bytes_to_bls_field function and test are done

* compute_powers function and test are done

* formatting

* Update eip_4844.rs

* clippy fixes

* Update fp2.rs

* formatting, uncommenting clippy

* #[allow(clippy::needless_borrow)] deleted

* Update eip_4844.rs

* Added vector_lincomb

* fixed vector_lincomb

* g1_lincomb and blob_to_kzg_commitment functions are added

* added fr_batch_inv and evaluate_polynomial

* Update eip_4844.rs

Co-authored-by: Matas <kirvaitism@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,190 +4,189 @@ on: [push]
 
 jobs:
   ci:
-
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         os: [ubuntu-latest, windows-latest, macos-11]
 
     steps:
-    - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-    - uses: actions-rs/toolchain@v1
-      with:
-        profile: minimal
-        toolchain: stable
-        components: clippy, rustfmt
+      - uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: stable
+          components: clippy, rustfmt
 
-# 1st team #########################################################
-        
-    - name: "[arkworks] Tests without parallel"
-      uses: actions-rs/cargo@v1
-      with:
-        command: test
-        args: --manifest-path Arkworks/Cargo.toml --no-fail-fast
+      # 1st team #########################################################
 
-    - name: "[arkworks] Tests with parallel"
-      uses: actions-rs/cargo@v1
-      with:
-        command: test
-        args: --manifest-path Arkworks/Cargo.toml --no-fail-fast --features parallel
+      - name: "[arkworks] Tests without parallel"
+        uses: actions-rs/cargo@v1
+        with:
+          command: test
+          args: --manifest-path Arkworks/Cargo.toml --no-fail-fast
 
-    - name: "[arkworks] Clippy"
-      uses: actions-rs/cargo@v1
-      with:
-        command: clippy
-        args: --manifest-path Arkworks/Cargo.toml --all-targets --all-features -- -D warnings
+      - name: "[arkworks] Tests with parallel"
+        uses: actions-rs/cargo@v1
+        with:
+          command: test
+          args: --manifest-path Arkworks/Cargo.toml --no-fail-fast --features parallel
 
-    - name: "[arkworks] Formatting"
-      uses: actions-rs/cargo@v1
-      with:
-        command: fmt
-        args: --manifest-path Arkworks/Cargo.toml
+      - name: "[arkworks] Clippy"
+        uses: actions-rs/cargo@v1
+        with:
+          command: clippy
+          args: --manifest-path Arkworks/Cargo.toml --all-targets --all-features -- -D warnings
 
-# 2nd team #########################################################
+      - name: "[arkworks] Formatting"
+        uses: actions-rs/cargo@v1
+        with:
+          command: fmt
+          args: --manifest-path Arkworks/Cargo.toml
 
-    - name: "[zkcrypto] Tests without parallelization"
-      uses: actions-rs/cargo@v1
-      with:
-        command: test
-        args: --manifest-path zkcrypto/Cargo.toml --no-fail-fast
-        
-    - name: "[zkcrypto] Tests with parallelization"
-      uses: actions-rs/cargo@v1
-      with:
-        command: test
-        args: --manifest-path zkcrypto/Cargo.toml --no-fail-fast --features parallel
+      # 2nd team #########################################################
 
-#    - name: "[zkcrypto] Clippy"
-#      uses: actions-rs/cargo@v1
-#      with:
-#       command: clippy
-#       args: --manifest-path zkcrypto/Cargo.toml --all-targets --all-features -- -D warnings
+      - name: "[zkcrypto] Tests without parallelization"
+        uses: actions-rs/cargo@v1
+        with:
+          command: test
+          args: --manifest-path zkcrypto/Cargo.toml --no-fail-fast
 
-    - name: "[zkcrypto] Formatting"
-      uses: actions-rs/cargo@v1
-      with:
-        command: fmt
-        args: --manifest-path zkcrypto/Cargo.toml
+      - name: "[zkcrypto] Tests with parallelization"
+        uses: actions-rs/cargo@v1
+        with:
+          command: test
+          args: --manifest-path zkcrypto/Cargo.toml --no-fail-fast --features parallel
 
-# 3rd team #########################################################
+      - name: "[zkcrypto] Clippy"
+        uses: actions-rs/cargo@v1
+        with:
+          command: clippy
+          args: --manifest-path zkcrypto/Cargo.toml --all-targets --all-features -- -D warnings
 
-    - name: "[blst-from-scratch] Tests"
-      uses: actions-rs/cargo@v1
-      with:
-        command: test
-        args: --manifest-path blst-from-scratch/Cargo.toml --no-fail-fast
+      - name: "[zkcrypto] Formatting"
+        uses: actions-rs/cargo@v1
+        with:
+          command: fmt
+          args: --manifest-path zkcrypto/Cargo.toml
 
-    - name: "[blst-from-scratch] Tests (parallel)"
-      uses: actions-rs/cargo@v1
-      with:
-        command: test
-        args: --manifest-path blst-from-scratch/Cargo.toml --no-fail-fast --features parallel
+      # 3rd team #########################################################
 
-    - name: "[blst-from-scratch] Clippy"
-      uses: actions-rs/cargo@v1
-      with:
-        command: clippy
-        args: --manifest-path blst-from-scratch/Cargo.toml --all-targets --all-features -- -D warnings
+      - name: "[blst-from-scratch] Tests"
+        uses: actions-rs/cargo@v1
+        with:
+          command: test
+          args: --manifest-path blst-from-scratch/Cargo.toml --no-fail-fast
 
-    - name: "[blst-from-scratch] Formatting"
-      uses: actions-rs/cargo@v1
-      with:
-        command: fmt
-        args: --manifest-path blst-from-scratch/Cargo.toml
+      - name: "[blst-from-scratch] Tests (parallel)"
+        uses: actions-rs/cargo@v1
+        with:
+          command: test
+          args: --manifest-path blst-from-scratch/Cargo.toml --no-fail-fast --features parallel
 
-# 4th team #########################################################
+      - name: "[blst-from-scratch] Clippy"
+        uses: actions-rs/cargo@v1
+        with:
+          command: clippy
+          args: --manifest-path blst-from-scratch/Cargo.toml --all-targets --all-features -- -D warnings
 
-    - name: "[ckzg] Build native libs for Linux"
-      if: matrix.os == 'ubuntu-latest'
-      run: |
-        echo "LIBOMP_PATH=$(find /usr/lib/llvm* -name libiomp5.so | head -n 1)" >> $GITHUB_ENV
-        echo "OMP_NUM_THREADS=$(nproc)" >> $GITHUB_ENV
-        cd ckzg && bash build.sh
+      - name: "[blst-from-scratch] Formatting"
+        uses: actions-rs/cargo@v1
+        with:
+          command: fmt
+          args: --manifest-path blst-from-scratch/Cargo.toml
 
-    - name: "[ckzg] Build native libs for MacOS"
-      if: matrix.os == 'macos-11'
-      run: |
-        brew install libomp gnu-sed
-        ln -s /usr/local/opt/libomp/lib/libomp.dylib /usr/local/lib
-        ln -s /usr/local/opt/libomp/include/omp.h /usr/local/include
-        echo "LIBOMP_PATH=/usr/local/lib/libomp.dylib" >> $GITHUB_ENV
-        echo "OMP_NUM_THREADS=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
-        cd ckzg && bash build.sh
+      # 4th team #########################################################
 
-    - name: "[ckzg] Setup Env"
-      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-11'
-      run: |
-        if [[ -z "$LIBOMP_PATH" ]]; then
-          echo "FAIL: LLVM OpenMP runtime was not found"
-          exit 1
-        fi
-        echo "RUSTFLAGS=-C link-arg="$LIBOMP_PATH"" >> $GITHUB_ENV
+      - name: "[ckzg] Build native libs for Linux"
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          echo "LIBOMP_PATH=$(find /usr/lib/llvm* -name libiomp5.so | head -n 1)" >> $GITHUB_ENV
+          echo "OMP_NUM_THREADS=$(nproc)" >> $GITHUB_ENV
+          cd ckzg && bash build.sh
 
-    - name: "[ckzg] Tests without parallelization"
-      uses: actions-rs/cargo@v1
-      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-11'
-      with:
-        command: test
-        args: --manifest-path ckzg/Cargo.toml --no-fail-fast
+      - name: "[ckzg] Build native libs for MacOS"
+        if: matrix.os == 'macos-11'
+        run: |
+          brew install libomp gnu-sed
+          ln -s /usr/local/opt/libomp/lib/libomp.dylib /usr/local/lib
+          ln -s /usr/local/opt/libomp/include/omp.h /usr/local/include
+          echo "LIBOMP_PATH=/usr/local/lib/libomp.dylib" >> $GITHUB_ENV
+          echo "OMP_NUM_THREADS=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
+          cd ckzg && bash build.sh
 
-    - name: "[ckzg] Tests with parallelization"
-      uses: actions-rs/cargo@v1
-      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-11'
-      with:
-        command: test
-        args: --manifest-path ckzg/Cargo.toml --no-fail-fast --features parallel
+      - name: "[ckzg] Setup Env"
+        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-11'
+        run: |
+          if [[ -z "$LIBOMP_PATH" ]]; then
+            echo "FAIL: LLVM OpenMP runtime was not found"
+            exit 1
+          fi
+          echo "RUSTFLAGS=-C link-arg="$LIBOMP_PATH"" >> $GITHUB_ENV
 
-    - name: "[ckzg] Clippy"
-      uses: actions-rs/cargo@v1
-      with:
-        command: clippy
-        args: --manifest-path ckzg/Cargo.toml --all-targets --all-features -- -D warnings
+      - name: "[ckzg] Tests without parallelization"
+        uses: actions-rs/cargo@v1
+        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-11'
+        with:
+          command: test
+          args: --manifest-path ckzg/Cargo.toml --no-fail-fast
 
-    - name: "[ckzg] Formatting"
-      uses: actions-rs/cargo@v1
-      with:
-        command: fmt
-        args: --manifest-path ckzg/Cargo.toml
+      - name: "[ckzg] Tests with parallelization"
+        uses: actions-rs/cargo@v1
+        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-11'
+        with:
+          command: test
+          args: --manifest-path ckzg/Cargo.toml --no-fail-fast --features parallel
 
-    - name: "[ckzg] Unset Env"
-      run: |
-        echo "RUSTFLAGS=" >> $GITHUB_ENV
-        echo "LIBOMP_PATH=" >> $GITHUB_ENV
+      - name: "[ckzg] Clippy"
+        uses: actions-rs/cargo@v1
+        with:
+          command: clippy
+          args: --manifest-path ckzg/Cargo.toml --all-targets --all-features -- -D warnings
 
-# 5th team ###########################################################
+      - name: "[ckzg] Formatting"
+        uses: actions-rs/cargo@v1
+        with:
+          command: fmt
+          args: --manifest-path ckzg/Cargo.toml
 
-    - name: "[mcl10-rust] Build mcl for Linux"
-      if: matrix.os == 'ubuntu-latest'
-      run: |
-        cd mcl/kzg && bash build.sh
+      - name: "[ckzg] Unset Env"
+        run: |
+          echo "RUSTFLAGS=" >> $GITHUB_ENV
+          echo "LIBOMP_PATH=" >> $GITHUB_ENV
 
-    - name: "[mcl10-rust] Run tests without parallel"
-      if: matrix.os == 'ubuntu-latest'
-      run: |
-        cargo test shared_tests --manifest-path mcl/kzg-bench/Cargo.toml --no-fail-fast -- --test-threads 1
+      # 5th team ###########################################################
 
-    - name: "[mcl10-rust] Run tests with parallel"
-      if: matrix.os == 'ubuntu-latest'
-      run: |
-        cargo test shared_tests --manifest-path mcl/kzg-bench/Cargo.toml --no-fail-fast --features mcl_rust/parallel -- --test-threads 1
+      - name: "[mcl10-rust] Build mcl for Linux"
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          cd mcl/kzg && bash build.sh
 
-    - name: "[mcl10-rust] Run Clippy"
-      if: matrix.os == 'ubuntu-latest'
-      uses: actions-rs/cargo@v1
-      with:
-        command: clippy
-        args: --manifest-path mcl/kzg/Cargo.toml --all-targets --all-features -- -D warnings
+      - name: "[mcl10-rust] Run tests without parallel"
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          cargo test shared_tests --manifest-path mcl/kzg-bench/Cargo.toml --no-fail-fast -- --test-threads 1
 
-    - name: "[mcl10-rust] Run fmt"
-      if: matrix.os == 'ubuntu-latest'
-      run: |
-        cargo fmt --manifest-path mcl/kzg-bench/Cargo.toml
+      - name: "[mcl10-rust] Run tests with parallel"
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          cargo test shared_tests --manifest-path mcl/kzg-bench/Cargo.toml --no-fail-fast --features mcl_rust/parallel -- --test-threads 1
 
-# Common ###########################################################
+      - name: "[mcl10-rust] Run Clippy"
+        if: matrix.os == 'ubuntu-latest'
+        uses: actions-rs/cargo@v1
+        with:
+          command: clippy
+          args: --manifest-path mcl/kzg/Cargo.toml --all-targets --all-features -- -D warnings
 
-    - uses: actions-rs/cargo@v1
-      with:
-        command: fmt
-        args: --manifest-path kzg-bench/Cargo.toml
+      - name: "[mcl10-rust] Run fmt"
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          cargo fmt --manifest-path mcl/kzg-bench/Cargo.toml
+
+      # Common ###########################################################
+
+      - uses: actions-rs/cargo@v1
+        with:
+          command: fmt
+          args: --manifest-path kzg-bench/Cargo.toml
